name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf87f76d953bdcb12c1d4c967a103c1a016c17c32aeb0b389eb9ceae1bfdec9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
