name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a27437a631343d38befe499b869df790542091e1178605ad2c113ccf085a2306"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
