name = "thumbpack"
author = "jack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6811bd3bccd55e549473ad94a7a1594006bce391567de1cc7bae0510087764d8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
